
# properties for the PRD environment
# properties defined here will override those in application.properties
# configuration of profiles: https://www.baeldung.com/spring-profiles

spring.datasource.url=jdbc:postgresql://BE-JORION-APP-PROD.resultinfra.com:5432/postgres
spring.datasource.username=trainingtool_prod
spring.datasource.password=TO_BE_REPLACED

app.server.domain=https://be-cvengine.resultinfra.com/
app.users.inmemory=true

