
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#transaction-properties

# Server
server.servlet.application-display-name=Training Tool
server.servlet.context-path=/trainingtool
server.servlet.session.timeout=1800

# Application parameters
spring.application.name=trainingtool

# Spring JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL82Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
# Disable Open-Session-In-View pattern
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.session_factory.interceptor=org.jorion.trainingtool.dao.TrackingInterceptor

# PostgreSQL DB
spring.datasource.initialize=false
spring.datasource.driver-class-name=org.postgresql.Driver

# Mailing Server properties
spring.mail.host=...
spring.mail.port=25
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.username=support@jorion.org
spring.mail.password=

# Spring Actuator: allow access to all endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.status.http-mapping.DOWN=200
management.endpoint.health.show-details=ALWAYS

# if the training has an effect on the billability of the member, should HR approve it ?
app.workflow.hrIfBillable=true

# Mail
app.mail.sendMail=true
# update this with hr emails
app.mail.address.hr=be.training@jorion.org
app.mail.address.training=be.training@jorion.org
app.mail.address.from=DONOTREPLY@jorion.org
app.mail.address.support=training.tool@jorion.org

# Roles
app.role.training=...
app.role.hr=...
app.role.manager=jorionb

# Misc.
# list of sectors
app.reg.sectors=Financial Services (FS),Energy & Utilities (E&U),Government (GOV),Health & Manufacturing (H&M),Management (MGT),Other
# display a warning message on the home page
app.msg.warning=true
# some functionalities may only be available locally (ex: H2)
app.local=false

# LDAP
ldap.url=ldap://...:389
ldap.basedn=OU=Users,OU=BE,OU=Landlord NL,OU=Corporate,DC=groupinfra,DC=com
