
server:
  servlet:
    session:
      timeout: '1800'
    application-display-name: Training Tool
    context-path: /trainingtool

spring:
  mail:
    username: support.trainingtool@example.org
    properties:
      mail:
        smtp:
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
          timeout: '5000'
    host: fr-smtp.resultinfra.com
    protocol: smtp
    password: ''
    port: '25'
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: 'false'
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: 'true'
          region:
            factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        session_factory:
          interceptor: org.jorion.trainingtool.dao.TrackingInterceptor
    open-in-view: 'false'
  application:
    name: trainingtool
  datasource:
    initialize: 'false'
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    displayOperationId: 'true'
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: org.jorion.trainingtool.controller

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      status:
        http-mapping:
          DOWN: '200'
      show-details: ALWAYS

app:
  local: 'false'
  reg:
    sectors: Financial Services (FS),Energy & Utilities (E&U),Government (GOV),Health
      & Manufacturing (H&M),Management (MGT),Other
  date:
    weeksToSubtract: '24'
    min: '2021-07-01'
  mail:
    address:
      from: DONOTREPLY@example.org
      hr: training.tool@example.org
      support: training.tool@example.org
      training: training.tool@example.org
    sendMail: 'true'
  role:
    manager: jorionb
    training: john.smith
    hr: john.smith
  msg:
    info: 'false'
  workflow:
    hrIfBillable: 'true'

ldap:
  basedn: OU=Users,OU=BE,OU=Landlord NL,OU=Corporate,DC=groupinfra,DC=com
  url: ldap://fr-ldap.resultinfra.com:389



