
# properties for the LOCAL environment
# properties defined here will override those in application.properties
# configuration of profiles: https://www.baeldung.com/spring-profiles

# Spring JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Datasource
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa

spring.datasource.initialize=true
spring.datasource.data=classpath:dbcr/h2-data.sql
spring.datasource.schema=classpath:dbcr/h2-schema.sql

# H2 Specific
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.server.domain=http://localhost:8080/
app.users.inmemory=true
app.users.ldap=false
app.local=true

