
# properties for the PRD environment
# properties defined here will override those in application.properties
# configuration of profiles: https://www.baeldung.com/spring-profiles

spring.datasource.url=jdbc:postgresql://...:5432/postgres
spring.datasource.username=******
spring.datasource.password=******

app.server.domain=https://be-cvengine.resultinfra.com/
app.users.inmemory=true

