
# properties for the TST environment
# properties defined here will override those in application.properties
# configuration of profiles: https://www.baeldung.com/spring-profiles

spring.datasource.url=jdbc:postgresql://BE-JORION-DEV-DB.resultinfra.com:5432/postgres
spring.datasource.username=trainingtool_test
spring.datasource.password=TO_BE_REPLACED

app.server.domain=http://be-cv-app-test.resultinfra.com:83/
app.users.inmemory=true

