
server:
  port: '8080'

spring:
  mail:
    username: support.trainingtool@example.org
    host: 162.70.14.76
    password: xxxxxxxxxxx

app:
  server:
    domain: http://localhost:8080/
  local: true
  mail:
    address:
      from: DONOTREPLY@example.org
      hr: bernard.jorion@example.org
      training: bernard.jorion@example.org
    sendMail: false
  role:
    admin: ''
    manager: jorionb
    hr: ''
  users:
    ldap: false
    inMemory: true




