
# This file will only be used locally
# It will NOT be included in the final fat-jar

# Server
server.port=8080

# We reuse the 'cvengine' permissions to access the SMTP server
spring.mail.host=...
spring.mail.username=...
spring.mail.password=...

# Application properties
# possible values: true, false
app.mail.sendMail=false
# specify the correct mail addresses below (comma-separated)
app.mail.address.hr=...
app.mail.address.training=...
app.mail.address.from=...

# Roles
app.role.admin=
app.role.hr=
app.role.manager=jorionb


ldap.url=ldap://...
